name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      working-directory: webpage

    - name: Build static site
      run: npm run build
      working-directory: webpage

    - name: Create gh-pages branch if it doesn't exist
      run: |
        git fetch origin
        if [ `git branch -r | grep 'origin/gh-pages'` ]; then
          git checkout gh-pages
        else
          git checkout --orphan gh-pages
          git reset --hard
          git commit --allow-empty -m "Initial commit"
          git push origin gh-pages
        fi

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
